[package]
name = "dokku-local-rust-musl-build-macos"
version = "0.1.0"
authors = ["Arve Seljebu <arve@seljebu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"